### ISSUE TITLE
All your stylesheets are gone

### ISSUE THREAD

**Issue by alg** [peritor/webistrano#1]
Am I insane, or you don't have any public/stylesheets since version 1.4?

**Comment by jweiss** [comment]
The stylesheets are dynamically generated. There is a Rails action in the Stylesheets controller to do this.

**Comment by alg** [comment]
Thanks. I am insane after all. Had an NGINX rule to take static files from public directly.

Now I can't get past the login screen. Even for stylesheets I get the application error. Should be something with gems... Even log isn't created.

Thanks for the hint!
