### ISSUE TITLE
Truncate method incompatible

### ISSUE THREAD

**Issue by alsotoes** [peritor/webistrano#27]
<b>Env:</b>
Gentoo Base System release 2.0.1 ( Vserver guest )

ruby --version
ruby 1.8.7 (2011-02-18 patchlevel 334) [i686-linux]

rails --version
Rails 3.0.7

<b>Error:</b>
ActionView::TemplateError (undefined method `length' for #Enumerable::Enumerator:0xe876ede4) on line #23 of app/views/users/_deployments.rhtml:
20:       <td><%= link_to h(deployment.task), project_stage_deployment_path(deployment.stage.project, deployment.stage, deployment) %></td>
21:       <td ><%=h deployment.created_at.to_s(:log)  %></td>
22:       <td><%=h deployment.completed_at.to_s(:log) rescue nil %></td>
23:       <td><%=h truncate(deployment.comment, 37) %></td>
24:       <td style="padding:3px 0px 0px 0px;" valign="middle" align="center"><%= image_tag('peritor_theme/'+deployment.status_image)%></td>
25:     </tr>
26:   <% end %>

<b>Steps to reproduce:</b>
1.- Configure a normal project.
2.- Configure stage
3.- Deploy it.
4.- Click in back o list the stage info... ( http://192.168.1.10:3000/projects/1/stages/1 )
5.- Error.....

**Comment by jweiss** [comment]
This is due to you using Rails 3.x, Webistrano only works with Rails 2.x.
Can you please try the latest master from git? 
It now uses bundler, so that the correct Rails version is always used.
