### ISSUE TITLE
fixed bundler version

### ISSUE THREAD

**Issue by gacha** [peritor/webistrano#28]
```
bundle install
Fetching source index for http://rubygems.org/
Bundler could not find compatible versions for gem "bundler":
  In Gemfile:
    bundler (= 1.0.10)

  Current Bundler version:
    bundler (1.0.13)
```

And installing the specified version of bundler doesn't solve the problem. I removed the bundler version number and all works. Maybe you can specify the bundler version with `~>` or `>=`.

**Comment by jweiss** [comment]
fixed with a98ba6b161ee5aedf4b7198a0a909be32bb0b9a6
