### ISSUE TITLE
ERROR,when create stage

### ISSUE THREAD

**Issue by liutaihua** [peritor/webistrano#29]
/home/wills/download/webistrano/vendor/bundler/ruby/1.8/gems/activerecord-2.3.11/lib/active_record/attribute_methods.rb:236:in `method_missing'
/home/wills/download/webistrano/lib/webistrano/deployer.rb:25:in`initialize'
/home/wills/download/webistrano/app/models/stage.rb:125:in `new'
/home/wills/download/webistrano/app/models/stage.rb:125:in`list_tasks'
/home/wills/download/webistrano/app/controllers/stages_controller.rb:17:in `show'
/home/wills/download/webistrano/app/controllers/application_controller.rb:24:in`set_timezone'

**Comment by ghost** [comment]
I am getting the same issue. Did you manage to resolve this? If so, how? :)

**Comment by liutaihua** [comment]
i guess,this error may be version of ruby, rails,rack.
on ubuntu ,i have this error,but on centos 5.4 sucessfully.

**Comment by jweiss** [comment]
what version of Webistrano is this? The latest official release or master of out git?

**Comment by ghost** [comment]
This is master out of git (I assume, I just cloned the github repository) as I couldn't find anything about an officla release.

**Comment by bollacker** [comment]
If this is an issues of versions, what are the exact "known good" versions of ruby, rails, rack?

**Comment by liutaihua** [comment]
I think the version of ruby,rails need to caption in README.

**Comment by eltonl** [comment]
There is no ruby version recommendations in README.txt

I am getting this error on Ubuntu 10.04 with Ruby 1.9.2

**Comment by cedriclombardot** [comment]
I've the same mistake with centos/ubuntu and ruby 1.8.7 or 1.9.3p0  how could i fix ?

**Comment by cedriclombardot** [comment]
For the moment, i've commented : 

lib/webistrano/deployer.rb:25

``` ruby
#if(@deployment.task ) #&& !@deployment.new_record?)
         # a read deployment
         @logger = Webistrano::Logger.new(deployment)
         @logger.level = Webistrano::Logger::TRACE
      #  validate
      #else
         # a fake deployment in order to access tasks
       # @logger = Capistrano::Logger.new
      #end
```

And it work, i've deployed

**Comment by eltonl** [comment]
hi Cedric

I have not had a chance to explore this further.  Were you able to define new projects and deployments within the interface after this mod or deploy projects you already had setup?

Thanks Elton

**Comment by cedriclombardot** [comment]
Hi,

I confirm with this patch i can do everything on my projects 

Cedric
