### ISSUE TITLE
Log output getting truncated

### ISSUE THREAD

**Issue by TravellingGuy** [peritor/webistrano#32]
We are using Webistrano to push out a PHP application, which generally works wonderfully.

However, some of the custom tasks we run during a deploy are quite verbose, printing lots of output.  I'm finding that Webistrano is truncating the log output after a few hundred lines.  i.e. we get a few hundred lines of output during deploys, then it just stops.  The deploy continues, but there's no more output.

As a result, if the deploy fails after the log output stops, we have no idea why.

Is there someway we can have Webistrano not truncate the log output and show the full log until the deploy finishes?

**Comment by pallan** [comment]
We had a similar problem and had to update the database column manually. From a TEXT to a LONGTEXT in MySQL.  Didn't investigate if there is a migration way to do it.

**Comment by TravellingGuy** [comment]
Ahh, that appears to be it.  Thanks pallan.

**Comment by jweiss** [comment]
Yes, changing the type to longtext fixes it. There is no way to do this nicely with migrations in an DB independent way...
