### ISSUE TITLE
undefined method `symlink' for class `Capistrano::Configuration::Namespaces::Namespace'

### ISSUE THREAD

**Issue by gm100861** [peritor/webistrano#54]
when i was run 
[root@node2 webistrano]# RAILS_ENV=production rake db:migrate  
rake aborted!
undefined method `symlink' for class`Capistrano::Configuration::Namespaces::Namespace'
/var/www/html/webistrano/config/initializers/capistrano_namespace_rake_fix.rb:2
/var/www/html/webistrano/config/initializers/capistrano_namespace_rake_fix.rb:2:in `class_eval'
/var/www/html/webistrano/config/initializers/capistrano_namespace_rake_fix.rb:2
/var/www/html/webistrano/vendor/bundler/ruby/1.8/gems/activesupport-2.3.11/lib/active_support/dependencies.rb:173:in`load_without_new_constant_marking'
/var/www/html/webistrano/vendor/bundler/ruby/1.8/gems/activesupport-2.3.11/lib/active_support/dependencies.rb:173:in `load'
/var/www/html/webistrano/vendor/bundler/ruby/1.8/gems/rails-2.3.11/lib/initializer.rb:622:in`load_application_initializers'
/var/www/html/webistrano/vendor/bundler/ruby/1.8/gems/rails-2.3.11/lib/initializer.rb:621:in `each'
/var/www/html/webistrano/vendor/bundler/ruby/1.8/gems/rails-2.3.11/lib/initializer.rb:621:in`load_application_initializers'
/var/www/html/webistrano/vendor/bundler/ruby/1.8/gems/rails-2.3.11/lib/initializer.rb:176:in `process'
/var/www/html/webistrano/vendor/bundler/ruby/1.8/gems/rails-2.3.11/lib/initializer.rb:113:in`send'
/var/www/html/webistrano/vendor/bundler/ruby/1.8/gems/rails-2.3.11/lib/initializer.rb:113:in `run'
/var/www/html/webistrano/config/environment.rb:16
/var/www/html/webistrano/vendor/bundler/ruby/1.8/gems/activesupport-2.3.11/lib/active_support/dependencies.rb:182:in`require'
/var/www/html/webistrano/vendor/bundler/ruby/1.8/gems/activesupport-2.3.11/lib/active_support/dependencies.rb:182:in `require'
/var/www/html/webistrano/vendor/bundler/ruby/1.8/gems/activesupport-2.3.11/lib/active_support/dependencies.rb:547:in`new_constants_in'
/var/www/html/webistrano/vendor/bundler/ruby/1.8/gems/activesupport-2.3.11/lib/active_support/dependencies.rb:182:in `require'
/var/www/html/webistrano/vendor/bundler/ruby/1.8/gems/rails-2.3.11/lib/tasks/misc.rake:4
Tasks: TOP => db:migrate => environment
(See full trace by running task with --trace)

[root@node2 webistrano]# bundle install
Fetching source index for http://rubygems.org/
Using rake (10.0.4) 
Using activesupport (2.3.11) 
Using rack (1.1.6) 
Using actionpack (2.3.11) 
Using actionmailer (2.3.11) 
Using activerecord (2.3.11) 
Using activeresource (2.3.11) 
Using bundler (1.0.22) 
Using highline (1.6.16) 
Using net-ssh (2.6.6) 
Using net-scp (1.1.0) 
Using net-sftp (2.1.1) 
Using net-ssh-gateway (1.2.0) 
Using capistrano (2.6.0) 
Using erubis (2.7.0) 
Using exception_notification (2.3.3.0) 
Installing json (1.7.7) with native extensions 
Using mocha (0.9.8) 
Using mysql (2.9.1) 
Using open4 (0.9.3) 
Using rails (2.3.11) 
Installing rdoc (4.0.1) 
Using syntax (1.0.0) 
Your bundle is complete! It was installed into ./vendor/bundler

i was chinese man,my english is not good. please help me . thanks a lot!

**Comment by gm100861** [comment]
OS Info:
[root@node2 webistrano]# cat /etc/issue
CentOS release 5.6 (Final)
Kernel \r on an \m

[root@node2 webistrano]# uname -a
Linux node2 2.6.18-238.el5 #1 SMP Thu Jan 13 15:51:15 EST 2011 x86_64 x86_64 x86_64 GNU/Linux

please help me ,please!

**Comment by caiosba** [comment]
It worked for me by removing config/initializers/capistrano_namespace_rake_fix.rb. Looks like this fix is not necessary anymore.
