### ISSUE TITLE
Order of config loading

### ISSUE THREAD

**Issue by tristanm** [peritor/webistrano#6]
In Websitrano::Deployer.set_up_config (lib/webistrano/deployer.rb, line 110) the order in which the config is loaded prohibits :webistrano_stage and :webistrano_project being used in other config variables such as :deploy_to.

For example, I want to set :deploy_to to "/path/to/deployments/#{application}/#{webistrano_stage}" but :webistrano_stage is not set until after these variables have been parsed.

I _think_ the fix is to change the order of loading in set_up_config from

```
set_stage_configuration(config)
set_stage_roles(config)
set_project_and_stage_names(config)
```

to

```
set_project_and_stage_names(config)
set_stage_configuration(config)
set_stage_roles(config)
```

This has worked so far for me but I didn't feel it was worth creating a fork and a pull request just for that little bit of code. Also, I don't know if this is going to break anything else further down the line.

Tristan

**Comment by jweiss** [comment]
I just committed your change.

Jonathan
